INSERT INTO INSTITUTION.COURSE (ID, Title, Description) VALUES (1, 'Computer Science', 'The study of computation, automation, and information.');
INSERT INTO INSTITUTION.COURSE (ID, Title, Description) VALUES (2, 'Management & Technology', 'An interdisciplinary course blending technology with business management.');
INSERT INTO INSTITUTION.COURSE (ID, Title, Description) VALUES (3, 'Electrical Engineering', 'The branch of engineering that deals with the technology of electricity.');
INSERT INTO INSTITUTION.COURSE (ID, Title, Description) VALUES (4, 'Biotechnology', 'The exploitation of biological processes for industrial and other purposes, especially the genetic manipulation of microorganisms.');
INSERT INTO INSTITUTION.COURSE (ID, Title, Description) VALUES (5, 'Mechanical Engineering', 'The branch of engineering dealing with the design, construction, and use of machines.');
INSERT INTO INSTITUTION.COURSE (ID, Title, Description) VALUES (6, 'Civil Engineering', 'A professional engineering discipline that deals with the design, construction, and maintenance of the physical and naturally built environment.');
INSERT INTO INSTITUTION.COURSE (ID, Title, Description) VALUES (7, 'Software Engineering', 'The application of engineering to the development of software in a systematic method.');
INSERT INTO INSTITUTION.COURSE (ID, Title, Description) VALUES (8, 'Environmental Science', 'An interdisciplinary academic field that integrates physical, biological and information sciences to the study of the environment.');
INSERT INTO INSTITUTION.COURSE (ID, Title, Description) VALUES (9, 'Psychology', 'The scientific study of the mind and behavior.');
INSERT INTO INSTITUTION.COURSE (ID, Title, Description) VALUES (10, 'Data Science', 'A multidisciplinary field that uses scientific methods, processes, algorithms, and systems to extract knowledge and insights from structured and unstructured data.');
