CREATE TABLE INSTITUTION.STUDENT (
	Id BIGINT PRIMARY KEY NOT NULL,
    Name VARCHAR NOT NULL,
    RollNumber VARCHAR NOT NULL,
    Dob TIMESTAMP NOT NULL
)
WITH "template=partitioned, backups=1, CACHE_NAME=Student,  VALUE_TYPE=com.bizremark.institution.student.model.entity.Student,CACHE_GROUP=Students, ATOMICITY=TRANSACTIONAL";
CREATE INDEX STUDENT_ID_IDX ON INSTITUTION.STUDENT (ID);